### ISSUE TITLE
Running bundle with NPM dep `cowsay` produces error `Cannot read properties of undefined (reading 'join')`

### ISSUE THREAD

**Issue by mattwelke** [vercel/ncc#1013]
I'm getting an error using a particular NPM dependency (`cowsay`), after I successfully ran a bundle with a different NPM dependency (`pg`).

Using dependencies:

```json
    "devDependencies": {
      "@vercel/ncc": "^0.34.0"
    },
    "dependencies": {
      "cowsay": "^1.5.0"
    }
```

Building with:

```json
    "scripts": {
      "build": "ncc build"
    },
```

Using source code:

```js
const cowsay = require('cowsay');

cowsay.say('Hello, World!');
```

After building with `npm build`, running the bundle with `node dist/index.js` produces the following output:

```
<path>/dist/index.js:173
        return balloon[action](options.text || options._.join(" "), options.n ? null : options.W) + "\n" + cow(face);

TypeError: Cannot read properties of undefined (reading 'join')
```

See https://github.com/mattwelke/repros/tree/main/ncc-cowsay-2022-12-03 for complete reproduction example.

Looking at past issues reported, https://github.com/vercel/ncc/issues/58 looks similar. There, they discuss static expressions and cite cowsay as an example where a change would help. I do notice that cowsay uses a directory of static assets and the error message appears to have to do with how those assets are referenced.

**Comment by styfle** [comment]
The same code fails without ncc so its likely a bug in your code

```
node index.js
```

See the correct usage here: https://www.npmjs.com/package/cowsay
