### ISSUE TITLE
Is option `target` also supported in programmatically way?

### ISSUE THREAD

**Issue by hugoalh** [vercel/ncc#1053]
Option `target` does mentioned in the [command's options](https://github.com/vercel/ncc#options) but not mentioned in the [programmatically way](https://github.com/vercel/ncc#programmatically-from-nodejs).

Thus, does option `target` also supported in programmatically way but just not mentioned, or in order to use option `target` then must use command instead?

**Comment by styfle** [comment]
It was missing from the docs.

Added in PR #1054
