### ISSUE TITLE
Detect which dependencies are bundled in a single distributed js file

### ISSUE THREAD

**Issue by AlexandreDecan** [vercel/ncc#1076]
Hello,

I've a (probably very naive) question about this tool. Given a generated file (say `dist/index.js`) that was created by vendoring some dependencies, is there a way to identify which where the dependencies used for creating this file? Said differently: can I detect which (external, npm) packages (and in which versions?) were bundled when the file was generated? 

Thank you :-)

**Comment by AlexandreDecan** [comment]
To put some context for this question: we are a team of researchers interesting in studying dependencies used for Actions in GitHub Actions. As far as we understand the process to create Actions, only a single `dist/index.js` file can be provided. We found that this file is usually generated from multiple source files and additional dependencies (usually expressed in `package.json`) and bundled together into a single output file. 

While we know we can extract the dependencies from the corresponding `package.json`, it happens that this manifest is not used at all to generate the `dist/index.js` file, implying that if we try to detect the dependencies used for `dist/index.js` based on the content of `package.json`, we will end up with an incorrect list of dependencies. So my naive question is: can we get the dependencies that were used to generate `dist/index.js` by looking solely at this file?

**Comment by styfle** [comment]
You can build with the “--source-map” flag to get source code information. 

ncc is currently using webpack under the hood so anything tools that could reverse webpack could also be used to analyze ncc output.

**Comment by AlexandreDecan** [comment]
Thanks! 

I'll have a look at what webpack does :-)
