### ISSUE TITLE
Fingerprinting?

### ISSUE THREAD

**Issue by Crisfole** [vercel/ncc#1099]
I'd like to use `ncc` for fingerprinting code. A code change in a given repo might change something about one module, but not another. If a given module changes I need to re-run that module over its source data, but if it doesn't I can continue to rely on my cached output.

I could obviously do this manually: build each module I care about with ncc and run the output through md5 or sha, but I was curious if this feature already existed.

**Comment by styfle** [comment]
You could try `--watch` 

https://github.com/vercel/ncc/blob/main/readme.md

**Comment by Crisfole** [comment]
Hm...This is during CI. I want a _hash_ so I know "did this module change." Thanks! Sounds like a manual process should work, though!
