### ISSUE TITLE
Getting `not a function` after compiling

### ISSUE THREAD

**Issue by soumyamahunt** [vercel/ncc#1114]
The reproducible sample can be found [here](https://github.com/SwiftyLab/setup-swift/tree/windows-perf) and the declaration giving error is [here](https://github.com/SwiftyLab/setup-swift/blob/1fa1bc57decf31a2ed3b61cd4fa513358bb27035/src/utils/visual_studio/update.ts#L16). This project is a Github action written is typescript, and when building with `tsc` or running unit tests (This method is covered as part of unit tests) I am not getting any error.

But after compiling and running this action I am getting [error](https://github.com/SwiftyLab/setup-swift/actions/runs/6111308127/job/16586277532?pr=46#step:3:625):
> visualStudio.update is not a function

Any fix or workaround possible for this?

**Comment by styfle** [comment]
You could try `--transpile-only`

**Comment by soumyamahunt** [comment]
> You could try `--transpile-only`

@styfle tried this option, don't see any change on the generated `index.js`.

**Comment by styfle** [comment]
Does it work without ncc, for example running node directly?

**Comment by soumyamahunt** [comment]
@styfle on further investigating, this seems more of issue with typescript. The object I created wasn't of the instance of the type the function was available in. For some reason, it worked with ts just by casting with `as`, I have refactored my code to fix this.

Sorry for the inconvenience, closing this issue as resolved.
