### ISSUE TITLE
ncc randomly copies folders from repository to dist (path.join + process.cwd)

### ISSUE THREAD

**Issue by Chakrygin** [vercel/ncc#1199]
Hi!

I encountered very strange behavior. I think this is a bug. Or I want to understand how to disable this behavior.

Apparently, if there is a line like this in the source code:

```ts
path.join(process.cwd(), 'some_folder')
```

Then this folder is copied to the dist folder.

For example, I have a simple repository, containing files:

package.json:
```json
{
    "private": true,
    "type": "module",
    "scripts": {
        "build": "ncc build ./src/main.ts --minify",
        "clean": "if exist dist rd /s /q dist > nul"
    },
    "devDependencies": {
        "@types/node": "^20.14.2",
        "@vercel/ncc": "^0.38.1",
        "typescript": "^5.4.5"
    }
}
```

tsconfig.json:
```json
{
}
```

src/main.ts:
```ts
import path from 'path';

console.log(
  path.join(process.cwd(), 'first'));

console.log(
  path.join(process.cwd(), 'second'));
```

And two empty text files:
- first/please-dont-copy-me-to-the-dist.txt
- second/please-dont-copy-me-to-the-dist.txt

After build I see this logs:
```
ncc: Version 0.38.1
ncc: Compiling file index.js into ESM
ncc: Using typescript@5.4.5 (local user-provided)
0kB  dist\package.json
0kB  dist\second/please-dont-copy-me-to-the-dist.txt
0kB  dist\first/please-dont-copy-me-to-the-dist.txt
1kB  dist\index.js
1kB  [2047ms] - ncc 0.38.1
```

And both files are copied:
![image](https://github.com/vercel/ncc/assets/6216874/f8883118-636a-419b-8fcb-c0596c71e325)

If I change main.ts file:

```ts
import path from 'path';

path.join(process.cwd(), 'first');
path.join(process.cwd(), 'second');
```

Then only the first file copied.

**Comment by Chakrygin** [comment]
It seems, there is workaround:

```ts
path.join(process.cwd(), 'some_folder'.toString())
```

**Comment by styfle** [comment]
This is expected behavior because file paths that exist are very likely to be read later.

To skip it, you can use `eval()` which is never statically analyzed.

Alternatively, you could delete the unwanted files after ncc runs.
