### ISSUE TITLE
NCC fails to pack project that uses latest version of null-writable

### ISSUE THREAD

**Issue by Vampire** [vercel/ncc#1217]
https://www.npmjs.com/package/null-writable changed to being an ESM module in v2.
Now it cannot be packed by NCC anymore.
With 1.0.5 packing works like a breeze.
But as soon as you use 2.0.0 or 2.0.1 of `null-writable`, you get the following error message:

```plain
ncc: Version 0.38.1
ncc: Compiling file index.js into ESM
Error: Module not found: Error: Default condition should be last one
Did you mean './null-writable'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
    at ...\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:38:1896272
    at ...\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:38:396262
    at _done (eval at create (...\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:21:75523), <anonymous>:9:1)
    at eval (eval at create (...\node_modules\@vercel\ncc\dist\ncc/index.js.cache.js:21:75523), <anonymous>:34:22)
```

**Comment by LoganArnett** [comment]
This is appears to be true for most ESM modules as I am seeing this same issue with the update in @middy/core
https://www.npmjs.com/package/@middy/core

**Comment by Vampire** [comment]
Actually, now I have it working, but I changed quite some things and don't know right now what change caused it to work now.

**Comment by styfle** [comment]
Closing as non-issue since the `null-writable` has an invalid package.json

- See https://github.com/dex4er/js-null-writable/pull/68
