### ISSUE TITLE
How to compile mjs to cjs

### ISSUE THREAD

**Issue by beliefgp** [vercel/ncc#1232]
i want type: module packages prebundle to commonjs

```
Error: For the selected environment is no default ESM chunk format available:
ESM exports can be chosen when 'import()' is available.
JSONP Array push can be chosen when 'document' is available.
```

**Comment by styfle** [comment]
This feature is not supported.

I suggest using `.cjs` as your input or set `type: commonjs` in package.json if you plan to use `.js` files.
