### ISSUE TITLE
How to use ncc with Typescript unit tests?

### ISSUE THREAD

**Issue by jbcpollak** [vercel/ncc#371]
We have a project with production code in the ./src directory and tests written in ./test. All code is written in Typescript.

Our Pre-ncc process is to compile everything to ./dist/{src|test}, then run our tests. When we switched our production code to build with ncc, our tests no longer have anything to compile against.

We are trying to figure out a best practice here. For now I think we need to keep our existing build process, then once the tests pass _rebuild_ with ncc, but that seems sub-optimal. 

Other options I've thought of all have other, worse downsides though:
- Compile each unit test as its one separate ncc project - this will probably be slow and redundant
- Compile test separately but have them import the compiled .js file - we lose all the typing
- .... ? other options?

**Comment by styfle** [comment]
> keep our existing build process, then once the tests pass rebuild with ncc, but that seems sub-optimal.

This is what we do for `now-builders`.

Does `ncc` take a long time to build for you?

**Comment by rauchg** [comment]
`ncc run` is a drop-in replacement for `node`. If you are able to `node` your tests, then you can `ncc run` your tests.
