### ISSUE TITLE
Allow customizing Webpack

### ISSUE THREAD

**Issue by timsuchanek** [vercel/ncc#405]
I would like to create a browser build of my code.
The easiest way to do so is probably being able to customize the webpack config.

**Comment by styfle** [comment]
Related https://github.com/zeit/now-builders/issues/308

**Comment by styfle** [comment]
You can achieve this today using [@now/static-build](https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build).

Just add a `now-build` script in your `package.json` file to invoke the webpack cli.

**Comment by talaikis** [comment]
+1, but I need custom Webpack for other purposes.

**Comment by styfle** [comment]
If you're using Next.js, you can configure webpack using `next.config.js`.

https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

For all other static sites, you can customize the Build Command to be whatever you wish, including custom webpack.

https://vercel.com/docs/build-step

**Comment by styfle** [comment]
I just realized that this issue is about `ncc` and not `vercel`.

Regardless, I'm going to keep it closed because `ncc` is not intended for browser bundles, its designed for Node.js.

**Comment by talaikis** [comment]
OK, I'm building for backend, not frontend. Anyway, I had forked ncc and made my custom changes.
