### ISSUE TITLE
Outputting an ES module / .mjs build

### ISSUE THREAD

**Issue by guybedford** [vercel/ncc#512]
We should be able to enable a `--module` flag or similar at this point that enables outputting an ES module instead of a CommonJS build.

**Comment by tunnckoCore** [comment]
The only possibility that I know for now is the `@purtuga/esm-webpack-plugin`, but the problem of with tree-shaking remains. As explained in the plugin readme.

**Comment by styfle** [comment]
Fixed in #720 by detecting `.mjs` or `type: module`
