### ISSUE TITLE
Optional chaining

### ISSUE THREAD

**Issue by webbertakken** [vercel/ncc#534]
Nextjs is already supporting optional chaining. I was hoping we could get it here too.

I would be willing to contribute if you can confirm this feature is wanted, in which case please do let me know where to start.

**Comment by styfle** [comment]
Absolutely we would accept a PR with optional chaining.

I believe the blocker here is upstream https://github.com/acornjs/acorn/pull/891

**Comment by Nabellaleen** [comment]
For information, it seems to works with TS, while targeting es2019 in tsconfig.json

**Comment by styfle** [comment]
This has been implemented, thanks!
