### ISSUE TITLE
Allow to customize webpack plugins

### ISSUE THREAD

**Issue by vitramir** [vercel/ncc#549]
I am trying to get Elastic APM ([elastic/apm-agent-nodejs](https://github.com/elastic/apm-agent-nodejs)) to work with ncc.

At this point the only solution I have found is the webpack plugin. [Here is the thread](https://github.com/elastic/require-in-the-middle/issues/35#issuecomment-637713594) regarding this issue.

Is it acceptable to add the ability to add custom webpack plugins? It violates the `Zero configuration` principe, but it may be acceptable to configure it when using a module, not CLI.

I can make PR for this feature

**Comment by lionelB** [comment]
@vitramir we use elastic apm with out bundle using this command 
```
NODE_ENV=production node -r elastic-apm-node/start ./dist/index.js",
```

**Comment by Zn4rK** [comment]
This would be a great feature! I'm happy to submit a PR for this!

**Comment by JustinFeng** [comment]
Any update on this? agreed, this will be a great feature if it can make `require-in-the-middle` work with `vercel/ncc` bundled js. 

In our case, we are using Datadog(which under the hood use require-in-the-middle to auto-instrument varies packages), as of now, we have to give up on ncc bundling to benefit from the auto instrumentation, which is sadly a tradeoff

**Comment by styfle** [comment]
There is no plan to expose webpack internals/plugins because that would make it near impossible to migrate from [webpack] to the successor, turbopack. See https://turbo.build/pack

> It violates the Zero configuration principle  

Correct. I suggest forking this repo if you want to configure webpack.
