### ISSUE TITLE
TypeORM

### ISSUE THREAD

**Issue by felipellrocha** [vercel/ncc#561]
I was not able to get my TypeORM project to work with NCC. Any ideas on how to make that work?

**Comment by itsdarrylnorris** [comment]
@felipellrocha ,

Do you have some example code? Or any error that you are getting?

**Comment by pliniopvv** [comment]
ncc remove the metadata which are necessary to typeorm function correctly.

<img width="931" height="844" alt="Image" src="https://github.com/user-attachments/assets/50ec765c-8fc4-4aa9-8856-94aa42f126a4" />

The class `SimplePost` is a very simple class of TypeORM service .
