### ISSUE TITLE
NCC does not pack licenses that are required to be included with their software

### ISSUE THREAD

**Issue by thboop** [vercel/ncc#569]
We are hoping to use NCC to pack a javascript project and it's `node_modules` into a single js file we can execute. However, when packing the `node_modules`, certain licenses require that they be included with the software, for example MIT states:
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Could we also package the licenses for each of these node modules in order to stay compliant with these licenses?

For example, webpack has: https://www.npmjs.com/package/license-webpack-plugin

**Comment by styfle** [comment]
Thanks for the suggestion!

Would you like to submit a PR to add this feature? Probably enable the plugin with the flag `--license`.

**Comment by bryancross** [comment]
@styfle This is going to be necessary for redistributing anything built with `ncc`....

**Comment by thboop** [comment]
Hey @styfle I've filed #570 , please let me know if there's anything else I can do to help!

Thanks so much!
