### ISSUE TITLE
Bug when compiling with Knex.js on windows 10

### ISSUE THREAD

**Issue by code-ape** [vercel/ncc#593]
We've run into a strange issue with code compilation by ncc resulting in a crashing program on Windows 10. A repo has been created that has been verified to exhibit this issue, here: https://github.com/urbdyn/ncc-bug-1

The bug results in code within Knex.js replacing string matches on imports with full paths. The repo has great amounts of detail and compiled output from a Windows and MacOS machine for comparison.

The resulting compiled code in question that seems to be resulting for this look like this on MacOS (works fine, non-buggy):

```js
/***/ 71330:
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

function __ncc_wildcard$0 (arg) {
  if (arg === "mssql") return __webpack_require__(19427);
  else if (arg === "mysql") return __webpack_require__(75941);
  else if (arg === "mysql2") return __webpack_require__(17653);
  else if (arg === "oracle") return __webpack_require__(9051);
  else if (arg === "oracledb") return __webpack_require__(25310);
  else if (arg === "postgres") return __webpack_require__(64482);
  else if (arg === "redshift") return __webpack_require__(97332);
  else if (arg === "sqlite3") return __webpack_require__(85370);
}
```

but for some reason is transformed into the following in a Windows environment:

```js
/***/ 71330:
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

function __ncc_wildcard$0 (arg) {
  if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(19427);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(75941);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(17653);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(9051);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(25310);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(64482);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(97332);
  else if (arg === "C:/code/urbdyn/ncc-bug-1/node_modules/knex/lib/dialects/") return __webpack_require__(85370);
}
```

As you can see, something very strange is occurring here which is resulting in a string comparison being replaced by the same directory path, in a hard coded manner.

I did do a bit of research on other issues in this repo and, after a bit more digging, that this seems to be a similar issue to #451.

Don't hesitate to let us know if you need any more information! Full environment details for the systems are given in the example repo.

Tagging @josh-josh-miller for visibility since he is also affected by this problem.

**Comment by dada513** [comment]
same issue here

**Comment by thiagoferolla** [comment]
Same here

**Comment by einsqing** [comment]
Same here

const newKnex = makeKnex(new Dialect(config));
                           ^

TypeError: Dialect is not a constructor

**Comment by microCloudCode** [comment]
Same here

**Comment by springJia** [comment]
same there

**Comment by code-ape** [comment]
This appears to have been resolved with ncc release `0.27.0`. My particular use case now works, though I'm unsure if this also has resolved others issues?

**Comment by kibertoad** [comment]
@microCloudCode Can you try the 0.27.0 and report back if you still experience a problem?

**Comment by einsqing** [comment]
> @microCloudCode Can you try the 0.27.0 and report back if you still experience a problem?

same issue on 0.27.0

**Comment by einsqing** [comment]
`const knex = require('knex')({
    client: require("knex/lib/dialects/sqlite3")
});`
This will work！

**Comment by styfle** [comment]
This was bumped in https://github.com/vercel/ncc/releases/tag/0.33.4
