### ISSUE TITLE
Question about  --license option

### ISSUE THREAD

**Issue by bc-lee** [vercel/ncc#599]
Hello, first of all, thanks for such a great project.

From my understanding, the `--license` option consolidates the license of third-party software, but that of the input source does not. Is it intended behavior, or it should be considered as a bug?

**Comment by styfle** [comment]
This is intended.

When you publish to npm, the root LICENSE of the repo is always published.

### Example

Lets say your repo looks like this:

```
README.md
LICENSE.txt
src/index.js
```

Then you run `ncc --license LICENSES.txt src/index.js`. Now you have:

```
README.md
LICENSE.txt
src/index.js
dist/index.js
dist/LICENSES.txt
```

After `npm publish` or `npm pack` you'll see:

```
README.md
LICENSE.txt
dist/index.js
dist/LICENSES.txt
```
