### ISSUE TITLE
Webpack 5 upgrade breaks

### ISSUE THREAD

**Issue by guybedford** [vercel/ncc#612]
The following Next.js packages break on the Webpack 5 upgrade:

* chalk
* etag
* raw-body
* node-fetch

It is definitely the ncc upgrade path that causes these dependency breaks, even if some of them are building and executing correctly.

We should investigate and fix these regressions.

**Comment by styfle** [comment]
@guybedford Is this still a problem with 0.25.1?

**Comment by guybedford** [comment]
The above don't really seem like browser packages to me, so I'm not sure the new option would help in these cases? Unless they are being pulled into the browser and breaking somehow.
