### ISSUE TITLE
ncc and devDependencies or dependencies or bundledDependencies

### ISSUE THREAD

**Issue by chmac** [vercel/ncc#620]
I'm building [a package](https://yarnpkg.com/package/git-remote-encrypted) with ncc.

I have 4 dependencies which are included in my ncc output. Where should these dependencies go in my `package.json` file?

Do they all go into `devDependencies`? Do they also go into `bundledDependencies`? I can't quite wrap my head around it and would be grateful for any input.

**Comment by Celtian** [comment]
I think that vercel is unable to solve situation when dependency has dependency that is not in your root package json.

**Comment by chmac** [comment]
@Celtian I'm wondering where dependencies should be placed for a package which is being built by ncc. Are they all dev dependencies? If somebody installs my package from npm they don't also need to install the dependencies which are bundled.

**Comment by Celtian** [comment]
I have already solve it. I was using @now/node-server instead of @vercel/node in my vercel.json. Problem was caused by this issue
https://github.com/amondnet/vercel-action/issues/61. Vercel should add also some warning message into the logs.

**Comment by chmac** [comment]
@Celtian I'm not sure what you're referring to. Maybe you're posting on the wrong issue?

I was asking a question about where to put dependencies. I'm not able to understand the connection between what you're posting and my issue. Maybe I'm missing something?

**Comment by Celtian** [comment]
vercel/ncc is ok. I though i was issu of this lib but it was caused by another package.

**Comment by henriqueleite42** [comment]
Same question here @chmac, and I also doesn't understand what @Celtian said :sweat_smile: 

I think that `bundleDependencies` are more correct than `devDependencies`, but I would like a more assertive answer.

Anyway, I will use `bundleDependencies` for now.

**Comment by styfle** [comment]
Use should use devDependencies if you’re publishing your package.json to npm. 

If you use the “--external” flag, then those should remain as normal dependencies.

**Comment by chmac** [comment]
Awesome, thanks for the confirmation @styfle. I'll update my original question with a summary and close the issue now.

**Comment by styfle** [comment]
[bundledDependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bundleddependencies) should probably be avoided since its a `npm pack` feature

**Comment by chmac** [comment]
@styfle You're absolutely right, updated my summary above, thanks. I misread thinking that this field signified which dependencies were bundled, rather than which `npm pack` should bundle. Got it now.
