### ISSUE TITLE
compile typescript file throw error could not load typescript compiler with NPM package name 

### ISSUE THREAD

**Issue by restuwahyu13** [vercel/ncc#622]
when I do ncc build an error appears like the following, is the problem related to the error below. thank you

ncc: Version 0.25.1
ncc: Compiling file index.js
Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
Error: Could not load TypeScript compiler with NPM package name `C:\Users\noname\Desktop\test\node_modules\@vercel\ncc\dist\ncc/typescript.js`. Are you sure it is correctly installed?

**Comment by restuwahyu13** [comment]
solved this issue, must be add **typescript** using **npm link** **typescript**

**Comment by PatrickAlphaC** [comment]
This did not solve it for me, I am seeing the same issue.
