### ISSUE TITLE
TypeScript interop needs tweaking

### ISSUE THREAD

**Issue by guybedford** [vercel/ncc#626]
The exact example at https://github.com/Timer/bundle-subasset does not actually work because the following TypeScript:

```js
import path from 'path';
path.resolve(...)
```

is transpiled by TypeScript into:

```js
const path = require('path');
path["default"].resolve(...)
```

which is clearly incorrect.

It does work if you use `import * as path from 'path'`.

We should adjust the TypeScript emission to use proper Node.js interop, which is a breaking change to make.

**Comment by sarink** [comment]
Is there any workaround that doesn't involve rewriting your imports? I'm trying to re-use an existing module in a monorepo.

**Comment by guybedford** [comment]
Fixed in https://github.com/vercel/ncc/pull/671.
