### ISSUE TITLE
Option to zip the results

### ISSUE THREAD

**Issue by donavon** [vercel/ncc#632]
Pushing to AWS Lambda requires a zip file. Would you be open to accepting a PR to add support to zip the results?

I was thinking of adding a `-z` (or `--zip`) build option. This would produce a zip file in the root using the name specified in `--out` (default = `dist`).

**Comment by styfle** [comment]
Thanks for the suggestion!

I think that zip/tar is outside the design goals of ncc so I'm going to close this.
