### ISSUE TITLE
bcrypt relocation not working 

### ISSUE THREAD

**Issue by adriencohen** [vercel/ncc#684]
Hello,

It looks like even after the fix in `webpack-asset-relocator-loader@1.2.3` to handle properly  `@mapbox/node-pre-gyp` ncc is still not able to relocate `bcrypt@5.0.1`.

I ran some tests by building locally ncc:

ncc@82bffab1df2c8936e1151352889a73434fd45dc4 (0.28.0 tag) - bcrypt correctly relocated ✅  
ncc@00cdc3f31a455dfa14c86f85c622776a31ab5ee2 (update to `webpack-asset-relocator-loader@1.2.3`) - bcrypt correctly relocated ✅  
ncc@446fc5645141fd119c120c766e33051bb3a4935b (before fix of webpack-asset-relocator-loader) - bcrypt  not relocated 🔴  

But when I use the `npm:@vercel/ncc@0.28.0` bcrypt is not relocated so I think there is an issue with packaged version.

**Comment by styfle** [comment]
Can you confirm 0.28.1 fixes the issue?

**Comment by adriencohen** [comment]
Looks good 👍

**Comment by eric-burel** [comment]
Hi, any idea what could cause `(node:83837) UnhandledPromiseRejectionWarning: Error: Cannot find module '/code/vulcan-next/.vn/scripts/db/lib/binding/napi-v3/bcrypt_lib.node'` when running the script? I use ncc 0.30.0 and bcrypt 5.0.1
