### ISSUE TITLE
SyntaxError: Unexpected token '}' on windows

### ISSUE THREAD

**Issue by UziTech** [vercel/ncc#689]
Upgrading from v0.28.0 to v0.28.2 in a github action

From the [log](https://github.com/UziTech/action-setup-atom/pull/186/checks?check_run_id=2310597856):

```
D:\a\action-setup-atom\action-setup-atom\dist\index.js:5239
/******/ })()
         ^

SyntaxError: Unexpected token '}'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

This seems to only happen on Microsoft Windows Server 2019 (currently windows-latest on github actions). I tested it on Window 10 and it ran just fine.

**Comment by styfle** [comment]
> This seems to only happen on Microsoft Windows Server 2019 (currently windows-latest on github actions). I tested it on Window 10 and it ran just fine.

That is odd. Can you confirm the Node.js version is the same on both? Perhaps its an outdated version in GH Actions?

**Comment by UziTech** [comment]
Node 14 on github-actions (where it fails). Node 15 on windows 10 (where it passes)

**Comment by styfle** [comment]
I created PR #691 to see if I could reproduce with CI but it doesn't get past `node-gyp`.

If you want to fix windows, PRs are welcome 🙂

**Comment by UziTech** [comment]
> it doesn't get past `node-gyp`.

Maybe this is the issue I am running into.

I can confirm that it works in v0.28.0 but not in v0.28.1+

**Comment by UziTech** [comment]
After much debugging I found that running the file output by @vercel/ncc (even in github actions windows-latest) it runs just fine, but when running the output as an action in github actions it fails with the above error (only on windows-latest).

It seems like this might be an issue with something that github actions injects into the output file.

**Comment by UziTech** [comment]
I tried building with @vercel/ncc manually to see if I could confirm it was github actions but the issue seems to only present itself when the build and run happen on github actions. I am at a loss for what to try next. I feel like github actions is doing something behind the scenes but I cannot figure out what.

Build and run on github actions fails:
![image](https://user-images.githubusercontent.com/97994/114451578-03272580-9b9d-11eb-9042-b9074564b71f.png)

Build manually and run on github actions passes:
![image](https://user-images.githubusercontent.com/97994/114451635-1639f580-9b9d-11eb-849a-9a5b2b0d6a6e.png)

**Comment by UziTech** [comment]
A little more debugging ... If I remove the shebang at the beginning of the file it works 😲!? even though the file ran fine in github actions with the shebang when built manually 🤷‍♂️

I'm going to close this as I don't believe it is an issue in @vercel/ncc
