### ISSUE TITLE
Force Include Module That Isn't Explicitly Imported

### ISSUE THREAD

**Issue by dvargas92495** [vercel/ncc#706]
I'm trying to build a package similar to [react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) but for a different niche. I have a `dev` command that I'd like to run `webpack-dev-server` with hot reloading. I am using `vercel/ncc` to build this package.

The problem I think I'm running into is that because `webpack-dev-server/client` is not explicitly imported in the package code, it gets excluded during tree shaking. Then when I try to use the package, I get a module not found error pointing to where I think `webpack-dev-server/client` should be.

My question is can there be a way to mark a module to be included in the bundle, even if they are not explicitly referenced? Somehow mark as "used in unknown way" or something like that?

**Comment by styfle** [comment]
You could try `require('webpack-dev-server/client')` so its explicit in your input file

**Comment by Twizzle1** [comment]
You could try, "require(" webpack-dev-service / client') so its explicit in your input file

**Comment by dvargas92495** [comment]
No longer need this

**Comment by Twizzle1** [comment]
Noted. The fork I proposed? Also noted. Check you later.

Sent via the Samsung Galaxy A03s, an AT&T 4G LTE smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
