### ISSUE TITLE
How can I execute the .cache only?

### ISSUE THREAD

**Issue by watch-janick** [vercel/ncc#717]
Hello,

I'm trying to compile my code into non-readable JS, and it looks like it's exactly what the `--v8-cache` option does, but in the generated `index.js` it needs the source code to run.

How can I run only with the `.cache` file?

Thanks!

**Comment by guybedford** [comment]
The v8 cache only caches the v8 profiling information needed to avoid the cold start. It doesn't include the full execution information which is still only available in the original source code.

**Comment by guybedford** [comment]
I'm going to close this, but happy to continue discussion.
