### ISSUE TITLE
How to include a file with ncc

### ISSUE THREAD

**Issue by arash-bizcover** [vercel/ncc#729]
I have a node app with the below structure:
![image](https://user-images.githubusercontent.com/62287461/125881878-5732f6bf-720c-4440-86a7-511b2d722684.png)

I cannot make it work with ncc, **Is there an option I can use to just bundle all the js files in the `./jobs` folder?**
 The reason is I'm dynamically loading files in `./jobs/` in my entrypoint `app.js`.
The structure and filenames of my jobs folder are important as I use them in my code.

I load all my job files dynamically like this, so I don't need to ever modify entrypoint `app.js`:

```javascript
const jobPath = require("path").join(__dirname, "jobs");
require("fs").readdirSync(jobPath).forEach(function (file) {
    let funcName = camelCase(file.replace(".js", ""))
    routes[funcName] = require(`./jobs/${file}`)[funcName]
});

```

**Comment by guybedford** [comment]
It's generally better in a scenario like this to explicitly list the jobs in the code - this way analysis tooling and bundlers can determine the dynamic import list without incorrectly guessing directory contents which might be loaded.

**Comment by arash-bizcover** [comment]
Appreciate your suggestion @guybedford 🙏 

But is there an option to include a file like this that is not detected automatically by ncc/webpack by force?

**Comment by guybedford** [comment]
@arash-bizcover even if we included the file, that wouldn't guarantee that the require would resolve the right thing as the output build file is in a different folder location to the input, so would get a different directory listing. So the bundler would need to understand every single line of code to correctly route the outcome. This is possible, and ncc effectively does this kind of rewriting currently so it's just an extension to ncc, but it is hard to ensure we don't include things we shouldn't.
