### ISSUE TITLE
How to use libraries which are pre provided in aws lambda like xml2js

### ISSUE THREAD

**Issue by ShivamJoker** [vercel/ncc#735]
I tried including the library with require as well as import but it doesn't seems to be working.

```js
import { parseStringPromise } from "xml2js";
```
I am getting module not found error unless I install the module explicitly 😞

**Comment by styfle** [comment]
`ncc build myfile.js --external xml2js` will exclude that package from the output

Otherwise you'll need to run `yarn add xml2js` to ensure it gets bundled

**Comment by ShivamJoker** [comment]
I guess it excludes it but there is some issue with lambda itself they aren't exposing other libraries except aws-sdk 😐

I even tried directly importing it in their editor

Anyway thanks I'll close this
