### ISSUE TITLE
ncc  not compile class property and throw error

### ISSUE THREAD

**Issue by restuwahyu13** [vercel/ncc#750]
```ts
../kraken-browser/esm/index.js 234:14
Module parse failed: Unexpected token (234:14)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|     class KrakenBrowser {
>       configs = {};
|       module = [];
|       input = [];
```

**Comment by guybedford** [comment]
ncc will compile private class fields fine, but it will not do Babel-style transformations to ensure support - that is up to you to ensure your code supports the target platform or separately run a Babel or transformer over it before or after running it through ncc.

**Comment by restuwahyu13** [comment]
Thanks for your response, @guybedford, I use transform plugin like this `@babel/plugin-proposal-class-properties`, and this is it's work
