### ISSUE TITLE
Missing dist/index.js since 0.27.0

### ISSUE THREAD

**Issue by PatrickHeneise** [vercel/ncc#758]
I'm using `ncc` for GitHub Actions written in `.mjs`. Running ncc version `0.27.0` always generated a `dist/index.js` file which was usable by GitHub Actions. Since then everything is compiled into `dist/index.mjs` which is unusable with the current Actions runtime. How do I get the previous behavior with `0.30.0`?

**Comment by styfle** [comment]
A `.mjs` input will create a `.mjs` output, this is not configurable through ncc

I suggest contacting someone at GitHub Actions if `.mjs` truly doesn't work.

You can also use `.ts` and with `target: commonjs` in tsconfig.json

**Comment by PatrickHeneise** [comment]
I'll check about `.mjs`. Not switching to `.ts` for this. Previous behavior was that `.mjs` produced an `index.js` file.
