### ISSUE TITLE
bug,dear sirs,you have changed our code when we your ncc

### ISSUE THREAD

**Issue by 564064202** [vercel/ncc#804]
we write software with nodejs 
we use process.cwd() to locate our process cwd ,but you changed the code ,lead our process can't find the config file

**Comment by 564064202** [comment]
require('../common/confing.js') 
does not equal 
require('../common/confing') 
in ncc

**Comment by 564064202** [comment]
@styfle 
require('../common/confing.js')
does not equal
require('../common/confing')
in ncc

**Comment by styfle** [comment]
It sounds like you might be using ESM instead of CJS, in which case this is expected behavior because Node.js requires a file extension for ESM imports.

https://nodejs.org/docs/latest-v16.x/api/esm.html

Its hard to say without full steps to reproduce
