### ISSUE TITLE
0.32.0 yields different output on different systems

### ISSUE THREAD

**Issue by awendt** [vercel/ncc#819]
I'm running `ncc build` on my local machine and it outputs 848kB. Github Actions is running `ncc build` and it outputs 530kB. I can reproduce the bigger local build with the exact same versions (Node v12.22.7, NPM 6.14.15) as on Github Actions.

This is highly unexpected because as part of our CI, we would like to make sure whatever is in `dist/` is up-to-date. But with this, we would have to download the build artifact instead of just generating it locally.

How can I make sure they have the same output?

**Comment by styfle** [comment]
Can you compare the contents of `node_modules` on both systems to make sure they are the same.

These can differ depending on the platform when you have native dependencies.

Also, its possible GitHub Actions includes additional `node_modules` which are then picked up by ncc.

**Comment by awendt** [comment]
Hi @styfle, didn't see your message until now, sorry about that!

`npm ls` shows the exact same output on both systems, so I guess we can rule out native dependencies. Github Actions has a *smaller* output than on my local machine, so additional packages there can't be the issue. 🤔

**Comment by styfle** [comment]
`npm ls` will always be the same with a lock file, its not sufficient to check the differences.

You would need to do a diff between `node_modules` directories.
