### ISSUE TITLE
"need an additional loader" when trying to compile Next.js app

### ISSUE THREAD

**Issue by nyg** [vercel/ncc#821]
Hello,

I created a simple Next.js app using `npx create-next-app`, added a [custom](https://nextjs.org/docs/advanced-features/custom-server) `server.js` file and tried to compile it using `ncc build server.js`. I'm having the following error:

```
ncc: Version 0.32.0
ncc: Compiling file index.js into CJS
Error: Module parse failed: Unexpected token (171:43)
File was processed with these loaders:
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
|                     entries[pageKey] = {
|                         bundlePath,
>                         __webpack_require__.ab + "_error.js",
|                         status: ADDED,
|                         lastActiveTime: Date.now(),
    at /Users/user/Desktop/test-ncc-nextjs/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1896789
    at /Users/user/Desktop/test-ncc-nextjs/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:353322
    at _done (eval at create (/Users/user/Desktop/test-ncc-nextjs/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:117937), <anonymous>:9:1)
    at eval (eval at create (/Users/user/Desktop/test-ncc-nextjs/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:117937), <anonymous>:34:22)
```

Is this the correct way to do it? Or should I first build the Next.js app using `next build` and then provide a generate Webpack file to ncc?

Thanks for the help, my knowledge of Webpack is very limited :).
nyg

```
{
  "name": "test-ncc-nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "12.0.4",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@vercel/ncc": "^0.32.0"
  }
}
```

Node v16.13.0

**Comment by styfle** [comment]
[Next.js 12](https://nextjs.org/blog/next-12#output-file-tracing) recently introduced a new feature called [Ouput file tracing](https://nextjs.org/docs/advanced-features/output-file-tracing).

There is some work being done by @ijjk to utilize the bundled output so that `ncc` will not be needed at all.

**Comment by nyg** [comment]
Hello, sorry, completely forgot to answer you! That's great news, waiting for it!
You mean that the ncc will be deprecated or something like this? or that simply it will not be needed for Next.js apps?

**Comment by styfle** [comment]
> simply it will not be needed for Next.js apps

Correct, Output File Tracing will be used for Next.js apps and there will be no need to use ncc if you're using Next.js
