### ISSUE TITLE
How to copy assets to output dir after build?

### ISSUE THREAD

**Issue by abcfy2** [vercel/ncc#829]
For example, I want to copy `src/assets/` to `dist/assets/` because my code use something like `fs.readFile('assets/test.txt')`

**Comment by styfle** [comment]
You can use `fs.readFile(path.join(__dirname, 'assets', 'test.txt'))` instead and then ncc will move it for you

**Comment by abcfy2** [comment]
Strange. I try to create an empty typescript project, it's working as you said.

But I try to add my project. It's not working:

I add these codes in my code (typescript):

```ts
export class MyClass {

  constructor(params: string) {
    console.log(__dirname);
    console.log(path.join(__dirname));
    console.log(path.join(__dirname, '..', '..', 'fonts', 'RousseauDeco.ttf'));
  }
```

`ncc run src/service/myclass.ts` will show:

```
ncc: Version 0.32.0
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.3.4 (local user-provided)
  40kB  sourcemap-register.js
3127kB  index.js
3503kB  index.js.map
6089kB  ipag.ttf
9256kB  [5906ms] - ncc 0.32.0
/tmp/f86b406c0fb706012bc1a6a8a0a0a66d
/tmp/f86b406c0fb706012bc1a6a8a0a0a66d
/fonts/RousseauDeco.ttf
```

`fonts/RousseauDeco.ttf` does not copy to output dir. Why?

**Comment by abcfy2** [comment]
Thanks. I solved my issue. Because I use google [gts](https://github.com/google/gts). Its default tsconfig contains `"module": "commonjs"`, https://github.com/google/gts/blob/main/tsconfig-google.json#L8

I try to add `"module": "ESNext"` in my `tsconfig.json`:

```json
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "dist",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "removeComments": true,
    "newLine": "lf",
    "noUnusedLocals": false,
    "useDefineForClassFields": true,
    "skipLibCheck": true,
    "lib": ["esnext"],
    "declaration": false,
    "module": "ESNext"  #<====== Add this config to override google gts default
  },
  "include": ["src/**/*.ts", "test/**/*.ts"]
}
```

Not it's working. Thank you very much.
