### ISSUE TITLE
Set NODE_ENV to 'production'

### ISSUE THREAD

**Issue by TiagoGouvea** [vercel/ncc#888]
I'm trying to set `process.env.NODE_ENV` on build time, but I cant get it to work. Following my build command on package.json:

`"build": "export NODE_ENV=production && NODE_ENV=production ncc build src/index.ts -o build"`

I'm forcing it twice on this command, but, I still getting an empty NODE_ENV on built code. 

Does ncc remove the NODE_ENV value during the build? How to set it right?

There is any other way to "know" that the running code is the built one?

**Comment by styfle** [comment]
ncc doesn't inline env vars so you'll need to set `NOD_ENV`  during build time and runtime

**Comment by TiagoGouvea** [comment]
Ok. I will proceed this way. Thank you.
