### ISSUE TITLE
How to ignore pagent.exe (and others)?

### ISSUE THREAD

**Issue by jeffrson** [vercel/ncc#901]
Apparently, as my package depends on SSH2 (https://www.npmjs.com/package/ssh2), ncc copies pagent.exe to the output folder. Also, I have local build tools (.exe on Windows) that are all copied to the output folder.

How can I prevent that?

ncc 0.33.3

**Comment by styfle** [comment]
ssh2 calls spawn on the exe so its included by ncc

https://github.com/mscdex/ssh2/blob/3f2c62d0861199d36f309464823443dea95869d3/lib/agent.js#L218

If you don't think that code path is executed, you can try manually deleting the file.
