### ISSUE TITLE
ncc command not found

### ISSUE THREAD

**Issue by airon-tark** [vercel/ncc#913]
Hey, guys!
I am going through the readme, and can't get it started.

```
$ npm i -g @vercel/ncc
/usr/local/Cellar/node/17.6.0_1/bin/ncc -> /usr/local/Cellar/node/17.6.0_1/lib/node_modules/@vercel/ncc/dist/ncc/cli.js
+ @vercel/ncc@0.33.4
updated 1 package in 0.363s

$ ncc build
zsh: command not found: ncc
```

Installed successfully, but then can't find the command

Thanks in advance

**Comment by airon-tark** [comment]
@styfle 

Thanks, it works!

**Comment by daniel-martensson** [comment]
I get the same on my Github Codespace, what to do then?
