### ISSUE TITLE
prevent ncc from shifting some files

### ISSUE THREAD

**Issue by sourcevault** [vercel/ncc#940]
Is it possible to prevent `ncc` from touching some files like `package.json` ?

now there are two `package.json` files ?

<img width="528" alt="upload" src="https://user-images.githubusercontent.com/20347647/176499822-3649fc31-2280-49aa-b7bd-c293494f791e.png">

**Comment by cb1kenobi** [comment]
@sourcevault In your top-level `package.json`, you wouldn't happen to have set `"type": "module"`?

**Comment by sourcevault** [comment]
but that requires creating the module as ES6 ?

**Comment by cb1kenobi** [comment]
@sourcevault I'm wondering is the `package.json` in the top-level of your project the same as the one in your `dist` directory and if the `package.json` in the top-level has `"type": "module"`.

**Comment by sourcevault** [comment]
> @sourcevault I'm wondering is the package.json in the top-level of your project the same as the one in your dist directory

yes

> package.json in the top-level has "type": "module".

no

**Comment by cb1kenobi** [comment]
Interesting. Appreciate the clarification. :)

**Comment by sourcevault** [comment]
You can view how I am using `ncc` here :

https://github.com/sourcevault/remotemon

`makefile ncc` and `bundle` folder.

For now I have no issue with how `ncc` is working.

`javascript` is the insane ex-wife that cannot be reasoned with and I understand  your predicament, but I can see how in large projects, `ncc` will have issues with debugging.

If you are using `ncc` it's best to design your software around it for the start, I suppose.
